### PR TITLE
Use dedicated disassembler instead of custom parser to fix "some instructions unknown" errors.

### PR DESCRIPTION
**Pull request by frerich**
I noticed that mach_override failed to instrument a few functions in the Tcl library, yielding a 'some instructions unknown!' message. Instead of extending the simplistic assembler instruction recognition even further, I decided to resolve this by throwing the custom code away and instead use a proper disassembler to recognize the statements.

I chose to use http://udis86.sourceforge.net/ which I used successfully in the past - it's also very lightweight, just a bunch of C files with no external dependencies (note how minimal the modification to the Rakefile is).

### CODE REVIEW

**Comment by rentzsch** [comment]
Nice, I didn't know the libudis86 project even existed!

**Comment by rentzsch** [comment]
I'm reintegrating your Pull Request into the unstable branch and boy libudis86 is a bitch to build? How did you build it? If I can't figure out something sane, I'm going to have to back out your Pull Request.

**Comment by rentzsch** [comment]
FWIW, here's my attempt to build it:

```
wolf-air1:udis86 wolf$ pwd
/Users/wolf/code/github/mach_override/dependancies/udis86
wolf-air1:udis86 wolf$ ./configure
-bash: ./configure: No such file or directory
wolf-air1:udis86 wolf$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I build/m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
configure.ac:29: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:44: error: possibly undefined macro: AC_DISABLE_SHARED
configure.ac:45: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:46: error: possibly undefined macro: AC_ENABLE_SHARED
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
autogen: autoreconf -i failed.
wolf-air1:udis86 wolf$ ./configure
configure: error: cannot find install-sh, install.sh, or shtool in build "."/build
wolf-air1:udis86 wolf$ 
```

I'm using homebrew with the latest of everything: autoconf 2.69, automake 1.14, cmake 2.8.11.2, pkg-config 0.28.

**Comment by frerich** [comment]
On 2013-08-30 02:01, rentzsch wrote:

> FWIW, here's my attempt to build it:
> 
> wolf-air1:udis86 wolf$ pwd
> /Users/wolf/code/github/mach_override/dependancies/udis86

Any particular reason you're trying to build a standalone copy of 
udis86? In any case, I never built the whole package, only the actual 
disassembler which is in the libudis86 subdirectory.

I never bothered trying the autoconf-based build system. The actual 
library is just a bunch of *.c files with no external dependencies. So 
you can either compile them in very easily (which is what I do in the 
project which also uses mach_override, and that's also what I did for 
the mach_override unit tests - see the Rakefile modification I did) but 
you could also build a shared library very easily. Here's what I just 
did with the udis86-1.7.1 tarball I got from udis86.sourceforge.net:

frerich@ubuntu:/tmp$ tar zxf libudis86-1.7.1.tar.gz
frerich@ubuntu:/tmp$ cd udis86-1.7.1
frerich@ubuntu:/tmp/udis86-1.7.1$ gcc -shared -o libudis86.so -I 
libudis86 libudis86/*.c
libudis86/udis86.c: In function ‘ud_init’:
libudis86/udis86.c:44:3: warning: incompatible implicit declaration of 
built-in function ‘memset’ [enabled by default]
frerich@ubuntu:/tmp/udis86-1.7.1$

That's all there is to it - you can get rid of that warning by defining 
HAVE_STRING_H (e.g. on the commandline).

> wolf-air1:udis86 wolf$ ./configure
> -bash: ./configure: No such file or directory
> wolf-air1:udis86 wolf$ ./autogen.sh
> autoreconf: Entering directory `.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal --force -I build/m4
> autoreconf: configure.ac: tracing
> autoreconf: configure.ac: not using Libtool
> autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf 
> --force
> configure.ac:29: error: possibly undefined macro: 
> AC_LIBTOOL_WIN32_DLL
>  If this token and others are legitimate, please use 
> m4_pattern_allow.
>  See the Autoconf documentation.
> configure.ac:44: error: possibly undefined macro: AC_DISABLE_SHARED
> configure.ac:45: error: possibly undefined macro: AC_PROG_LIBTOOL
> configure.ac:46: error: possibly undefined macro: AC_ENABLE_SHARED
> autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with
> exit status: 1

...this sounds like the build system maybe requires a particular 
autoconf macro or so? In any case, I wouldn't even bother trying to 
build it, IMHO using autoconf for such a tiny project is way overkill. 
:-}

## 

Frerich Raabe - raabe@froglogic.com
www.froglogic.com - Multi-Platform GUI Testing

**Comment by rentzsch** [comment]
Hi @frerich,

First off, thanks for taking the time for helping me through this.

I agree a project this size doesn't need autoconf, but what are ya gonna do? :)

You're right I don't want to compile the whole udis86, I was just trying to walk in through their frontdoor.

Thanks to your help I figured out the tarball download from the SourceForge site differs significantly from the GitHub tagged release (the GitHub release doesn't include itab.h, which is needed by udis86.h).

I was going to use git-subtree to pull in their repo directly, which would make upgrading better. But that looks like a pipe dream.

**Pull request merged**
