### PR TITLE
Fix x86 builds on Clang 3.2/Xcode 4.6.

### PR DESCRIPTION
**Pull request by jorgenpt**
This fixes a build issue with the latest unstable.

In addition, 1.x doesn't build either, but I left that untouched since it seems like the unstable branch is fine.

### CODE REVIEW

**Comment by rentzsch** [comment]
Thanks @jorgenpt!

**Comment by jorgenpt** [comment]
@rentzsch, is there a reason to not use OSAtomicCompareAndSwap64Barrier?

E.g.:

```
void atomic_mov64(
        uint64_t *targetAddress,
        uint64_t value)
{
        while (true)
        {
                uint64_t old_value = *targetAddress;
                if (OSAtomicCompareAndSwap64Barrier(old_value, value, (int64_t*)targetAddress)) return;
        }
}
```

I've had some issues with the assembly + naked instruction stuff, this seems cleaner and more robust.

**Comment by rentzsch** [comment]
I seem to recall OS-supplied atomic functions weren't easily available to userland back when mach_override was originally written for PowerPC. If they're available, fer sure we can and should use them.

But it looks like `OSAtomicCompareAndSwap64Barrier` is in `libkern/OSAtomic.h`? Doesn't that mean it's intended for kernel extensions? If so, linking would be problematic.

Probably some equivalent functions that are intended for userland code?

**Comment by jorgenpt** [comment]
They don't require any special linking - they're present in libc. :)

**Comment by rentzsch** [comment]
Huh, I didn't know that. Toss me a Pull Request and I'll merge it right in. :)

**Comment by rentzsch** [comment]
huh, this is broken for me for me on 10.8.4/Xcode 4.6.3. If I back up to 195c13743fe0ebc658714e2a9567d86529f20443 then unstable branch passes `rake`. Is it working for you? Bad on me if I accepted your Pull Request w/o testing it first.

**Comment by jorgenpt** [comment]
I tested it locally and it seemed to work, then I shipped it to all of our costumers and something was definitely broken.

I didn't realize there was a test suite until I did my `OSAtomicCompareAndSwap64Barrier` change. I've since shipped a new update with code like the code in https://github.com/rentzsch/mach_override/pull/13. That pull request passes the `rake' test.

**Comment by rentzsch** [comment]
Yeah, I just noticed #13 passes. I'll just merge that, thanks.

**Comment by jorgenpt** [comment]
Sorry for breaking your software!

**Comment by rentzsch** [comment]
heh, no problem. My bad for not testing -- I made it easy for myself. No excuse.

**Pull request merged**
