### PR TITLE
Simplify fixupInstructions

### PR DESCRIPTION
**Pull request by espindola**
Looks like I need to add suport for

call foo
foo:
pop %eax

In onder to run the testcase on 10.8 32 bits with clang. I still have to test it a bit more, but I think this refactoring can go in first.

### CODE REVIEW

**Comment by rentzsch** [comment]
OK I merged it, but in the unstable branch.

**Comment by rentzsch** [comment]
Oh, forgot to mention: the basic tests now pass on my end.

**Comment by espindola** [comment]
On 11 August 2012 01:49, Jonathan 'Wolf' Rentzsch
notifications@github.com wrote:

> Oh, forgot to mention: the basic tests now pass on my end.

They work for me on 64 bits, but not yet in 32 bits on 10.8. I will
try to send a pull request today with a fix and then debug what went
wrong with the original patches.

Cheers,
Rafael

**Comment by rentzsch** [comment]
Yup, I added more basic tests (https://github.com/rentzsch/mach_override/commit/4619c1989b9fa193ff92864853db6a6427cdc5da) and it's failing for me again for clang i386 and clang x86_64.

**Pull request closed without merging**
